import type { Question } from './components/types'

const questions: Question[] = [
  {
    id: 'q1',
    title: 'How do I center a div in CSS?',
    description: 'I need a responsive way to center a div both horizontally and vertically inside its parent container.',
    author_id: 'u1',
    is_solved: false,
    allow_ai_companion: true,
    vote_count: 14,
    created_at: '2026-05-10T08:15:00Z',
    author: { id: 'u1', username: 'frontend_dev' },
    question_tags: [{ tag: { name: 'css' } }, { tag: { name: 'layout' } }],
    answers: [
      {
        id: 'a1',
        body: 'Use display:flex on the parent and align-items:center; justify-content:center; on the container.',
        question_id: 'q1',
        author_id: 'u2',
        vote_count: 8,
        is_accepted: true,
        is_ai_generated: false,
        created_at: '2026-05-10T09:00:00Z',
        author: { id: 'u2', username: 'css_master' },
        comments: [
          {
            id: 'c1',
            body: 'Works great when the parent has a fixed height.',
            target_id: 'a1',
            target_type: 'answer',
            created_at: '2026-05-10T09:10:00Z',
            author: { username: 'helper' },
          },
        ],
      },
    ],
    comments: [
      {
        id: 'c2',
        body: 'Are you using flexbox or grid?',
        target_id: 'q1',
        target_type: 'question',
        created_at: '2026-05-10T08:20:00Z',
        author: { username: 'commenter1' },
      },
    ],
  },
  {
    id: 'q2',
    title: 'What is the best way to fetch data in React?',
    description: 'I want to load data from an API when a component mounts, and then show a loading state.',
    author_id: 'u3',
    is_solved: true,
    allow_ai_companion: true,
    vote_count: 22,
    created_at: '2026-05-09T13:48:00Z',
    author: { id: 'u3', username: 'react_student' },
    question_tags: [{ tag: { name: 'react' } }, { tag: { name: 'api' } }],
    answers: [
      {
        id: 'a2',
        body: 'Use useEffect with an async fetch inside, and store the result in state with useState.',
        question_id: 'q2',
        author_id: 'u4',
        vote_count: 19,
        is_accepted: true,
        is_ai_generated: false,
        created_at: '2026-05-09T14:05:00Z',
        author: { id: 'u4', username: 'react_guru' },
        comments: [],
      },
    ],
    comments: [],
  },
  {
    id: 'q3',
    title: 'How can I improve SQL query performance?',
    description: 'My query is slow on large tables. Which indexes should I add and how can I check the execution plan?',
    author_id: 'u5',
    is_solved: false,
    allow_ai_companion: false,
    vote_count: 7,
    created_at: '2026-05-11T07:02:00Z',
    author: { id: 'u5', username: 'db_admin' },
    question_tags: [{ tag: { name: 'sql' } }, { tag: { name: 'performance' } }],
    answers: [],
    comments: [
      {
        id: 'c3',
        body: 'Try EXPLAIN ANALYZE to see which step is the bottleneck.',
        target_id: 'q3',
        target_type: 'question',
        created_at: '2026-05-11T07:15:00Z',
        author: { username: 'query_wizard' },
      },
    ],
  },
  {
    id: 'q4',
    title: 'How do I implement user authentication with JWT tokens in a Node.js Express application?',
    description: 'I need to add secure login functionality to my web app using JSON Web Tokens for session management.',
    author_id: 'u6',
    is_solved: false,
    allow_ai_companion: true,
    vote_count: 12,
    created_at: '2026-05-11T10:30:00Z',
    author: { id: 'u6', username: 'backend_dev' },
    question_tags: [{ tag: { name: 'nodejs' } }, { tag: { name: 'authentication' } }, { tag: { name: 'jwt' } }],
    answers: [],
    comments: [],
  },
]

export default questions
